Improve config options and header placement, add more imgui_xeno_init callbacks
RoccoDev/imgui-xeno pull request #3
Opened 2023-10-08 23:47 UTC by BlockBuilder57

Apologies that this is not multiple PRs, I never made one for the older commits and it's too late at this point.

This adds #ifndef directives around all of the backend config options, so compilers can override the existing config options without having to fork the library. Along those lines, helper functions (notably, the ones for InputHelper) were moved into the include directory. This allows the files to be overwritten somewhat, which allowed me to access the input from Xenomods without having to entirely change my version of the nn headers.

The third commit here is a breaking change - new callbacks for imgui_xeno_init. The existing (post)init was split into pre and post, and a pre new frame callback has also been introduced. I've been having troubles loading new fonts from a file, and this change enables that to occur. (FWIW, The best way I've found is just adding the fonts before initializing the backend.) I _think_ I've updated all instances of imgui_xeno_init in the README/examples, but let me know if I missed something.

2023-10-12 10:13 UTC, RoccoDev requested changes
I've left some notes wrt naming and API compatibility. Looks good otherwise.

More standard backends would let the user handle initialization instead of callbacks, but we're already using a non-standard approach to begin with.

2023-10-12 10:13 UTC, RoccoDev commented on include/imgui_xeno.h
> +extern "C" void imgui_xeno_init(InitFunc preInitCallback, InitFunc postInitCallback, NewFrameFunc newFrameCallback, ProcDrawFunc renderCallback);
We can keep compatibility with the old API by making the new callbacks optional, by keeping `imgui_xeno_init` as it was, and adding new `imgui_xeno_set_on_...` functions. (or `add_on_...` if we allow multiple callbacks)

2023-10-12 10:13 UTC, RoccoDev commented on README.md
> +    fn imgui_xeno_init(preInit: *const c_void, postInit: *const c_void, newFrame: *const c_void, draw: *const c_void);
These names (and their usages/references in Rust files) should be snake case, i.e. `pre_init` etc.

Same for the exported functions in the same file.

2023-11-02 15:51 UTC, BlockBuilder57 commented
Sorry for not getting to this until now, I've been incredibly busy. This should be good with what you've requested, let me know if there are any other changes to make.

2023-11-02 20:43 UTC, RoccoDev requested changes
One small typo in the otherwise excellent documentation, ready to merge after this.

Thanks again!

2023-11-02 20:43 UTC, RoccoDev commented on include/imgui_xeno.h
> + * Optionally egisters a callback that is executed just before the start of every frame.
```suggestion
 * Optionally registers a callback that is executed just before the start of every frame.
```

2023-11-02 22:01 UTC, BlockBuilder57 commented on include/imgui_xeno.h
> + * Optionally egisters a callback that is executed just before the start of every frame.
me when i egister

2023-11-02 22:02 UTC, BlockBuilder57 commented
Fixed, sorry about that!

2023-11-02 22:03 UTC, merged